"""Add AI content fields to dossier_sections

Revision ID: 5f1b38086393
Revises: 6484ae625cb0
Create Date: 2026-03-12 19:01:11.402413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f1b38086393'
down_revision = '6484ae625cb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dossier_sections', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('dossier_sections', sa.Column('content_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('dossier_sections', sa.Column('placeholder_content', sa.Text(), nullable=True))
    op.add_column('dossier_sections', sa.Column('ai_extracted_content', sa.Text(), nullable=True))
    op.add_column('dossier_sections', sa.Column('ai_confidence_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dossier_sections', 'ai_confidence_score')
    op.drop_column('dossier_sections', 'ai_extracted_content')
    op.drop_column('dossier_sections', 'placeholder_content')
    op.drop_column('dossier_sections', 'content_requirements')
    op.drop_column('dossier_sections', 'content')
    # ### end Alembic commands ###