"""Add file_hash column to uploaded_files

Revision ID: 6484ae625cb0
Revises: 53724c723f03
Create Date: 2026-03-12 13:49:20.097381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6484ae625cb0'
down_revision = '53724c723f03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('file_hash', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_files', 'file_hash')
    # ### end Alembic commands ###